import os
import ycm_core

def FlagsForFile( filename, **kwargs ):
    # A bit hacky, but will do the job for a single OP-TEE tree
    dirname = "/home/jbech/devel/optee_projects/qemu/optee_os"

    return {
            'flags': [ 
                '-DARM32=1',
                '-D__ILP32__=1',
                '-D__KERNEL__',
                '-DTRACE_LEVEL=3',
                '-fdata-sections',
                '-fdiagnostics-show-option',
                '-ffunction-sections',
                '-fno-common',
                '-fno-short-enums',
                '-funwind-tables',
                '-g',
                '-g3',
                '-I', dirname + '/core/arch/arm/include',
                '-I', dirname + '/core/arch/arm/plat-vexpress',
                '-I', dirname + '/core/include',
                '-I', dirname + '/core/lib/libfdt/include',
                '-I', dirname + '/core/lib/libtomcrypt/include',
                '-I', dirname + '/lib/libmpa/include',
                '-I', dirname + '/lib/libutee/include',
                '-I/home/jyx/devel/optee_os/lib/libutee/include',
                '-I', dirname + '/lib/libutils/ext/include',
                '-I', dirname + '/lib/libutils/isoc/include',
                '-I', dirname + '/out/arm/core/arch/arm/tee',
                '-I', dirname + '/out/arm/core/include/generated',
                '-include',
                '-isystem',
                '-mcpu=cortex-a15',
                '-MD',
                '-MF',
                '-mfloat-abi=soft',
                '-mno-unaligned-access',
                '-MT',
                '-mthumb',
                '-mthumb-interwork',
                '-nostdinc',
                '-O0',
                '-pedantic',
                '-pipe',
                '-std=gnu99',
                '-Waggregate-return',
                '-Wall',
                '-Wcast-align',
                '-Wdeclaration-after-statement',
                '-Werror',
                '-Werror-implicit-function-declaration',
                '-Wextra',
                '-Wfloat-equal',
                '-Wformat=2',
                '-Wformat-nonliteral',
                '-Wformat-security',
                '-Winit-self',
                '-Wmissing-declarations',
                '-Wmissing-format-attribute',
                '-Wmissing-include-dirs',
                '-Wmissing-noreturn',
                '-Wmissing-prototypes',
                '-Wnested-externs',
                '-Wno-format-zero-length',
                '-Wno-missing-field-initializers',
                '-Wold-style-definition',
                '-Wpointer-arith',
                '-Wredundant-decls',
                '-Wshadow',
                '-Wstrict-aliasing=2',
                '-Wstrict-prototypes',
                '-Wswitch-default',
                '-Wundef',
                '-Wwrite-strings',
                '-x', 'c',
                '-isystem', '/lib/clang/5.0.0/include',
                '-isystem', '/usr/lib/llvm-4.0/lib/clang/4.0.1/include',
                '',
                ],
                'do_cache': True,
            }

